### ISSUE TITLE
Already exists.

### ISSUE THREAD

**Issue by Mar0xy** [nalsai/flat-manager-docker#1]
There is already an official dockerized version of flat-manager under `bilelmoussaoui/flatpak-github-actions/flat-manager` on docker hub which is part of https://github.com/flatpak/flatpak-github-actions

**Comment by nalsai** [comment]
Thanks for the issue! The one you linked is a setup for building flatpaks along with a flat-manager-client for uploading it to the server. This repo is supposed to be the flat-manager server from the latest master (I plan on using it together with what you linked). There is already <https://github.com/elementary/flat-manager-docker/>, but it doesn't build from the latest master due to depending on a newer version of ostree which isn't in the repos of alpine.

**Comment by nalsai** [comment]
If you can run the flat-manager server from there, could you maybe share a simple setup for running it, as I couldn't find any documentation about it. (The step with `uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3` clearly runs the flat-manager-client)
